//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi.net2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MediTrackEntities : DbContext
    {
        private static MediTrackEntities _context;
        public MediTrackEntities()
            : base("name=MediTrackEntities")
        {
        }
        public static MediTrackEntities GetContext()
        {
            if (_context == null)
                _context = new MediTrackEntities();
            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ambulance> ambulance { get; set; }
        public virtual DbSet<RolesUser> RolesUser { get; set; }
        public virtual DbSet<Uchet> Uchet { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<UserData> UserData { get; set; }
    }
}
