//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mi.net2
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int Id { get; set; }
        public string LoginUser { get; set; }
        public string PassUser { get; set; }
        public int RoleId { get; set; }
    
        public virtual RolesUser RolesUser { get; set; }
    }
}
